spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=public"
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 54320
