spring:
  datasource:
    url: "jdbc:postgresql://localhost:54320/postgres?currentSchema=public"
    username: postgres
    password: localPostgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 42100
