spring:
  datasource:
    url: "jdbc:postgresql://localhost:5435/1ommy?currentSchema=public"
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8006

logging:
  level:
    org:
      hibernate:
        type: trace
