spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=public"
    username: postgres
    password: webwelle32
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 42100
